apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mariadb
  labels:
    app: {{ .Release.Name }}-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mariadb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mariadb
    spec:
      containers:
      - name: mariadb
        image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
        imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: {{ .Values.mariadb.auth.rootPassword }}
        - name: MARIADB_USER
          value: {{ .Values.mariadb.auth.username }}
        - name: MARIADB_PASSWORD
          value: {{ .Values.mariadb.auth.password }}
        - name: MARIADB_DATABASE
          value: {{ .Values.mariadb.auth.database }}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mariadb-pvc
