apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-wordpress-pvc
  labels:
    app: {{ .Release.Name }}-wordpress
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mariadb.persistence.storageClass }}
  storageClassName: {{ .Values.mariadb.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mariadb-pvc
  labels:
    app: {{ .Release.Name }}-mariadb
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mariadb.persistence.storageClass }}
  storageClassName: {{ .Values.mariadb.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size }}
