{{- if .Values.secrets.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    app: {{ .Release.Name }}-mariadb
type: Opaque
stringData:
  mariadb-root-password: {{ .Values.mariadb.auth.rootPassword | quote }}
  mariadb-password: {{ .Values.mariadb.auth.password | quote }}
  mariadb-user: {{ .Values.mariadb.auth.username | quote }}
  mariadb-database: {{ .Values.mariadb.auth.database | quote }}
{{- end }}
