medusa:
  image:
    repository: ghcr.io/shivang-16/shopflow-medusa
    tag: latest
    pullPolicy: Always
  
  resources:
    requests:
      memory: "768Mi"
      cpu: "300m"
    limits:
      memory: "1.5Gi"
      cpu: "800m"
  
  service:
    type: NodePort
    port: 9000
    nodePort: null
  
  env:
    NODE_ENV: "production"
    ADMIN_CORS: "*"
    STORE_CORS: "*"
    DATABASE_URL: ""
    REDIS_URL: ""
  
  readinessProbe:
    enabled: false
  
  livenessProbe:
    enabled: false

ingress:
  enabled: false
  className: "nginx"
  host: "medusa.yourdomain.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  tls:
    enabled: true
    secretName: medusa-tls-secret

resourceQuota:
  enabled: true
  hard:
    requests.cpu: "800m"
    requests.memory: "1.5Gi"
    limits.cpu: "1.5"
    limits.memory: "3Gi"
    persistentvolumeclaims: "2"

networkPolicy:
  enabled: false
  policyTypes:
    - Ingress
    - Egress

secrets:
  createSecret: true
