{{- if .Values.postgresql }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app: {{ .Release.Name }}-postgresql
    app.kubernetes.io/name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgresql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgresql
        app.kubernetes.io/name: postgresql
    spec:
      {{- if .Values.postgresql.securityContext }}
      securityContext:
        {{- toYaml .Values.postgresql.securityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: postgresql
        image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
        imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.auth.database | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.auth.username | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresql.auth.password | quote }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgresql
        {{- if .Values.postgresql.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        {{- end }}
        {{- if .Values.postgresql.resources }}
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.postgresql.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
              {{- toYaml .Values.postgresql.readinessProbe.exec.command | nindent 14 }}
          initialDelaySeconds: {{ .Values.postgresql.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.postgresql.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.postgresql.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.postgresql.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.postgresql.readinessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.postgresql.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
              {{- toYaml .Values.postgresql.livenessProbe.exec.command | nindent 14 }}
          initialDelaySeconds: {{ .Values.postgresql.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.postgresql.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.postgresql.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.postgresql.livenessProbe.failureThreshold }}
        {{- end }}
      {{- if .Values.postgresql.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-postgresql-pvc
      {{- end }}
{{- end }}
