{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Name }}-limits
spec:
  limits:
  - default:
      cpu: {{ .Values.limitRange.default.cpu | quote }}
      memory: {{ .Values.limitRange.default.memory | quote }}
    defaultRequest:
      cpu: {{ .Values.limitRange.defaultRequest.cpu | quote }}
      memory: {{ .Values.limitRange.defaultRequest.memory | quote }}
    type: Container
{{- end }}
