apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    app: {{ .Release.Name }}-medusa
type: Opaque
stringData:
  {{- if .Values.medusa.env.DATABASE_URL }}
  database-url: {{ .Values.medusa.env.DATABASE_URL | quote }}
  {{- else if .Values.postgresql }}
  database-url: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}?sslmode=disable"
  {{- else }}
  database-url: ""
  {{- end }}
  {{- if .Values.medusa.env.REDIS_URL }}
  redis-url: {{ .Values.medusa.env.REDIS_URL | quote }}
  {{- else if .Values.redis }}
  redis-url: "redis://{{ .Release.Name }}-redis:6379"
  {{- else }}
  redis-url: ""
  {{- end }}
