apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    app: {{ .Release.Name }}-medusa
type: Opaque
stringData:
  database-url: {{ .Values.medusa.env.DATABASE_URL | quote }}
  redis-url: {{ .Values.medusa.env.REDIS_URL | quote }}
