apiVersion: v1
kind: Secret
metadata:
  name: {{ include "medusa.fullname" . }}-secret
  labels:
    app: {{ .Release.Name }}-medusa
type: Opaque
stringData:
  {{- if .Values.medusa.env.DATABASE_URL }}
  DATABASE_URL: {{ .Values.medusa.env.DATABASE_URL | quote }}
  {{- else if .Values.postgresql }}
  DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}?sslmode=disable"
  {{- else }}
  DATABASE_URL: ""
  {{- end }}
  {{- if .Values.medusa.env.REDIS_URL }}
  REDIS_URL: {{ .Values.medusa.env.REDIS_URL | quote }}
  {{- else if .Values.redis }}
  REDIS_URL: "redis://{{ .Release.Name }}-redis:6379"
  {{- else }}
  REDIS_URL: ""
  {{- end }}
