apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    app: {{ .Release.Name }}-medusa
type: Opaque
stringData:
  postgres-user: {{ .Values.postgresql.auth.username | quote }}
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  postgres-database: {{ .Values.postgresql.auth.database | quote }}
  database-url: "postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
  redis-url: "redis://{{ .Release.Name }}-redis:6379"
