apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app: {{ .Release.Name }}-postgresql
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
  selector:
    app: {{ .Release.Name }}-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: {{ .Release.Name }}-redis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-medusa
  labels:
    app: {{ .Release.Name }}-medusa
spec:
  type: {{ .Values.medusa.service.type }}
  ports:
  - port: {{ .Values.medusa.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}-medusa
