apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-medusa
  labels:
    app: {{ .Release.Name }}-medusa
spec:
  type: {{ .Values.medusa.service.type }}
  ports:
  - port: {{ .Values.medusa.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.medusa.service.type "NodePort") .Values.medusa.service.nodePort }}
    nodePort: {{ .Values.medusa.service.nodePort }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}-medusa
